interface FieldDef {
  key: string;
  label: string;
  type: "text" | "textarea" | "json" | "tags" | "select" | "date" | "number";
  options?: string[];
  placeholder?: string;
  tableVisible?: boolean;
}

export const FIELD_DEFS: Record<string, FieldDef[]> = {
  company_intelligence: [
    { key: "what_they_sell", label: "What They Sell", type: "textarea" },
    { key: "who_they_sell_to", label: "Who They Sell To", type: "textarea" },
    { key: "why_they_win", label: "Why They Win", type: "textarea" },
    { key: "why_they_lose", label: "Why They Lose", type: "textarea" },
    { key: "business_goal", label: "Business Goal", type: "textarea" },
    { key: "gtm_challenge", label: "GTM Challenge", type: "textarea" },
    { key: "product_overview", label: "Product Overview", type: "textarea" },
    { key: "sales_handoff_notes", label: "Sales Handoff Notes", type: "json" },
    {
      key: "seasonal_intelligence",
      label: "Seasonal Intelligence",
      type: "json",
    },
    { key: "win_loss_log", label: "Win/Loss Log", type: "json" },
    {
      key: "icp_validation_notes",
      label: "ICP Validation Notes",
      type: "json",
    },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
    },
  ],
  voice_model: [
    { key: "founder_name", label: "Founder Name", type: "text" },
    { key: "founder_linkedin", label: "Founder LinkedIn", type: "text" },
    {
      key: "brand_tone_summary",
      label: "Brand Tone Summary",
      type: "textarea",
    },
    {
      key: "communication_style",
      label: "Communication Style",
      type: "textarea",
    },
    { key: "credible_topics", label: "Credible Topics", type: "tags" },
    { key: "avoid_topics", label: "Topics to Avoid", type: "tags" },
    { key: "phrases_they_use", label: "Phrases They Use", type: "tags" },
    { key: "phrases_they_avoid", label: "Phrases They Avoid", type: "tags" },
    { key: "sample_content_good", label: "Good Sample Content", type: "json" },
    { key: "sample_content_bad", label: "Bad Sample Content", type: "json" },
    { key: "approved_language", label: "Approved Language", type: "tags" },
    { key: "legal_claims", label: "Legal Claims", type: "tags" },
    { key: "channel_voice_notes", label: "Channel Voice Notes", type: "json" },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
    },
  ],
  hubspot_health: [
    { key: "portal_id", label: "Portal ID", type: "text" },
    { key: "hubspot_tier", label: "HubSpot Tier", type: "text" },
    { key: "last_data_hygiene", label: "Last Data Hygiene", type: "date" },
    { key: "contact_db_stats", label: "Contact DB Stats", type: "json" },
    { key: "pipeline_config", label: "Pipeline Config", type: "json" },
    { key: "automation_status", label: "Automation Status", type: "json" },
    {
      key: "lc_custom_properties",
      label: "LC Custom Properties",
      type: "json",
    },
    { key: "integrations", label: "Integrations", type: "json" },
    { key: "known_issues", label: "Known Issues", type: "json" },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
    },
  ],
  review_rules: [
    { key: "auto_execute_rules", label: "Auto-Execute Rules", type: "tags" },
    { key: "lc_review_rules", label: "LC Review Rules", type: "tags" },
    {
      key: "client_signoff_rules",
      label: "Client Sign-off Rules",
      type: "tags",
    },
    { key: "custom_rules", label: "Custom Rules", type: "json" },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
    },
  ],
  sow_scope: [
    { key: "contract_start", label: "Contract Start", type: "date" },
    { key: "contract_end", label: "Contract End", type: "date" },
    { key: "monthly_retainer", label: "Monthly Retainer ($)", type: "number" },
    { key: "billing_cycle", label: "Billing Cycle", type: "text" },
    {
      key: "status",
      label: "Contract Status",
      type: "select",
      options: ["active", "paused", "churned", "upsell"],
    },
    { key: "services_in_scope", label: "Services In Scope", type: "json" },
    { key: "deliverables", label: "Deliverables", type: "json" },
    { key: "out_of_scope", label: "Out of Scope", type: "tags" },
    { key: "escalation_path", label: "Escalation Path", type: "textarea" },
    { key: "renewal_notes", label: "Renewal Notes", type: "textarea" },
    { key: "discrepancies", label: "Discrepancies", type: "textarea" },
  ],
  lc_edge_benchmarks: [
    { key: "email_benchmarks", label: "Email Benchmarks", type: "json" },
    { key: "linkedin_benchmarks", label: "LinkedIn Benchmarks", type: "json" },
    {
      key: "paid_media_benchmarks",
      label: "Paid Media Benchmarks",
      type: "json",
    },
    { key: "sales_benchmarks", label: "Sales Benchmarks", type: "json" },
    { key: "share_of_voice", label: "Share of Voice", type: "json" },
  ],
  icp_definitions: [
    { key: "name", label: "ICP Name", type: "text", tableVisible: true },
    {
      key: "company_size_range",
      label: "Company Size",
      type: "select",
      options: ["1-50", "51-200", "201-500", "501-1000", "1000+"],
      tableVisible: true,
    },
    { key: "industry_vertical", label: "Industry Verticals", type: "tags" },
    { key: "geography", label: "Geography", type: "tags" },
    {
      key: "funding_type",
      label: "Funding Type",
      type: "select",
      options: ["bootstrapped", "pe_backed", "vc_backed", "public"],
    },
    { key: "tech_stack_signals", label: "Tech Stack Signals", type: "tags" },
    { key: "buying_triggers", label: "Buying Triggers", type: "json" },
    { key: "deal_size_range", label: "Deal Size Range", type: "text" },
    { key: "avg_sales_cycle", label: "Avg Sales Cycle", type: "text" },
    { key: "disqualifiers", label: "Disqualifiers", type: "tags" },
    {
      key: "priority",
      label: "Priority",
      type: "select",
      options: ["primary", "secondary", "tertiary"],
      tableVisible: true,
    },
    { key: "tam_estimate", label: "TAM Estimate", type: "text" },
    {
      key: "customer_list_loaded",
      label: "Customer List Loaded",
      type: "select",
      options: ["true", "false"],
    },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
      tableVisible: true,
    },
  ],
  personas: [
    { key: "name", label: "Persona Name", type: "text", tableVisible: true },
    { key: "title_variants", label: "Title Variants", type: "tags" },
    {
      key: "priority",
      label: "Priority",
      type: "select",
      options: ["primary", "secondary", "tertiary"],
      tableVisible: true,
    },
    {
      key: "buying_role",
      label: "Buying Role",
      type: "select",
      options: [
        "economic_buyer",
        "influencer",
        "champion",
        "blocker",
        "end_user",
      ],
      tableVisible: true,
    },
    { key: "pain_points", label: "Pain Points", type: "tags" },
    { key: "values", label: "Values", type: "tags" },
    { key: "research_channels", label: "Research Channels", type: "tags" },
    { key: "contact_preference", label: "Contact Preference", type: "text" },
    {
      key: "communication_style",
      label: "Communication Style",
      type: "textarea",
    },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
      tableVisible: true,
    },
  ],
  competitive_map: [
    {
      key: "competitor_name",
      label: "Competitor Name",
      type: "text",
      tableVisible: true,
    },
    { key: "positioning", label: "Positioning", type: "textarea" },
    { key: "strengths", label: "Strengths", type: "textarea" },
    { key: "weaknesses", label: "Weaknesses", type: "textarea" },
    { key: "recent_moves", label: "Recent Moves", type: "textarea" },
    { key: "differentiators", label: "Differentiators", type: "textarea" },
    { key: "win_loss_summary", label: "Win/Loss Summary", type: "textarea" },
    { key: "objections", label: "Objections", type: "json" },
    {
      key: "watch_priority",
      label: "Watch Priority",
      type: "select",
      options: ["watch_closely", "monitor", "low_priority"],
      tableVisible: true,
    },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
      tableVisible: true,
    },
  ],
  message_matrix: [
    { key: "label", label: "Label", type: "text", tableVisible: true },
    {
      key: "dimension",
      label: "Dimension",
      type: "select",
      options: ["persona", "market_condition", "icp"],
      tableVisible: true,
    },
    { key: "core_message", label: "Core Message", type: "textarea" },
    {
      key: "pain_point_addressed",
      label: "Pain Point Addressed",
      type: "textarea",
    },
    { key: "proof_point", label: "Proof Point", type: "textarea" },
    { key: "cta", label: "CTA", type: "text" },
    { key: "objections_response", label: "Objection Responses", type: "json" },
    { key: "sample_language", label: "Sample Language", type: "textarea" },
    {
      key: "section_status",
      label: "Status",
      type: "select",
      options: ["draft", "lc_reviewed", "client_approved", "needs_refresh"],
      tableVisible: true,
    },
    { key: "message_version", label: "Version", type: "number" },
  ],
  content_index: [
    { key: "title", label: "Title", type: "text", tableVisible: true },
    {
      key: "format",
      label: "Format",
      type: "select",
      options: [
        "blog",
        "case_study",
        "white_paper",
        "video",
        "webinar",
        "infographic",
        "email",
        "social_post",
        "press_release",
        "analyst_report",
        "index",
        "podcast",
        "speaking_engagement",
      ],
      tableVisible: true,
    },
    { key: "url", label: "URL", type: "text" },
    { key: "date_published", label: "Date Published", type: "date" },
    { key: "channel", label: "Channel", type: "text" },
    {
      key: "performance_category",
      label: "Performance",
      type: "select",
      options: [
        "best_performing",
        "solid",
        "underperformed",
        "content_graveyard",
      ],
      tableVisible: true,
    },
    { key: "performance_notes", label: "Performance Notes", type: "textarea" },
    {
      key: "is_proof_point",
      label: "Is Proof Point",
      type: "select",
      options: ["true", "false"],
    },
    { key: "proof_point_type", label: "Proof Point Type", type: "text" },
    {
      key: "proof_point_summary",
      label: "Proof Point Summary",
      type: "textarea",
    },
    {
      key: "repurpose_potential",
      label: "Repurpose Potential",
      type: "textarea",
    },
    { key: "owner", label: "Owner", type: "text" },
    { key: "status", label: "Content Status", type: "text" },
  ],
  campaign_history: [
    { key: "name", label: "Campaign Name", type: "text", tableVisible: true },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: ["active", "completed", "paused", "cancelled"],
      tableVisible: true,
    },
    { key: "channels", label: "Channels", type: "tags" },
    {
      key: "start_date",
      label: "Start Date",
      type: "date",
      tableVisible: true,
    },
    { key: "end_date", label: "End Date", type: "date" },
    { key: "goal", label: "Goal", type: "textarea" },
    { key: "result", label: "Result", type: "textarea" },
    { key: "worked", label: "What Worked", type: "textarea" },
    { key: "key_metrics", label: "Key Metrics", type: "json" },
    { key: "lessons_learned", label: "Lessons Learned", type: "textarea" },
  ],
  key_contacts: [
    { key: "name", label: "Name", type: "text", tableVisible: true },
    {
      key: "side",
      label: "Side",
      type: "select",
      options: ["client", "lc"],
      tableVisible: true,
    },
    { key: "title", label: "Title", type: "text", tableVisible: true },
    { key: "role", label: "Role", type: "text" },
    { key: "email", label: "Email", type: "text" },
    { key: "phone", label: "Phone", type: "text" },
    {
      key: "is_primary",
      label: "Primary Contact",
      type: "select",
      options: ["true", "false"],
      tableVisible: true,
    },
    { key: "communication_prefs", label: "Communication Prefs", type: "json" },
    { key: "personality_notes", label: "Personality Notes", type: "textarea" },
  ],
  goals_backwards_math: [
    { key: "period", label: "Period", type: "text", tableVisible: true },
    {
      key: "revenue_target",
      label: "Revenue Target ($)",
      type: "number",
      tableVisible: true,
    },
    { key: "avg_deal_size", label: "Avg Deal Size ($)", type: "number" },
    { key: "win_rate", label: "Win Rate (%)", type: "number" },
    {
      key: "required_pipeline",
      label: "Required Pipeline ($)",
      type: "number",
    },
    { key: "required_sqls", label: "Required SQLs", type: "number" },
    { key: "sql_conversion_rate", label: "SQL Conv. Rate (%)", type: "number" },
    { key: "required_mqls", label: "Required MQLs", type: "number" },
    { key: "mql_conversion_rate", label: "MQL Conv. Rate (%)", type: "number" },
    {
      key: "required_top_of_funnel",
      label: "Required Top of Funnel",
      type: "number",
    },
    { key: "monthly_mql_target", label: "Monthly MQL Target", type: "number" },
    { key: "current_pipeline", label: "Current Pipeline ($)", type: "number" },
    { key: "current_mqls", label: "Current MQLs", type: "number" },
    {
      key: "on_track",
      label: "On Track",
      type: "select",
      options: ["green", "yellow", "red"],
      tableVisible: true,
    },
    { key: "goal_notes", label: "Notes", type: "textarea" },
  ],
};
